#!/bin/sh
# Copyright (c) 2015 by Roderick W. Smith
# Copyright (c) 2021 by profzei
# Copyright (c) 2024 by null2264
# Licensed under the terms of the GPL v3

case $OSTYPE in darwin*) >&2 echo "Signing from macOS is currently not possible"; exit 1 ;; esac;

# 0.8.7
VERSION=$1

[ -z "$1" ] && { echo "Usage: download-signed-opencore [version]"; exit 1; }

# Download and unzip OpenCore
wget "https://github.com/acidanthera/OpenCorePkg/releases/download/${VERSION}/OpenCore-${VERSION}-RELEASE.zip"
unzip "OpenCore-${VERSION}-RELEASE.zip" "X64/*" -d "./Downloaded"
rm "OpenCore-${VERSION}-RELEASE.zip"

# Download HfsPlus
wget https://github.com/acidanthera/OcBinaryData/raw/master/Drivers/HfsPlus.efi -O ./Downloaded/X64/EFI/OC/Drivers/HfsPlus.efi

[ -f "./ISK.key" ] && echo "ISK.key was decrypted successfully" || { echo "ISK.key not found, cancelling..."; exit 1; }

[ -f "./ISK.pem" ] && echo "ISK.pem was decrypted successfully" || { echo "ISK.pem not found, cancelling..."; exit 1; }

# Sign drivers by recursively looking for the .efi files in ./Downloaded directory
# Don't sign files that start with the dot, as this is metadata files
# Andrew Blitss's contribution
find ./Downloaded/X64/EFI/**/* -type f -name "*.efi" ! -name '.*' | cut -c 3- | xargs -I{} bash -c 'sbsign --key ISK.key --cert ISK.pem --output $(mkdir -p $(dirname "./Signed/{}") | echo "./Signed/{}") ./{}'

# Clean
rm -rf Downloaded
echo "Cleaned..."
