#!/bin/sh

case $OSTYPE in darwin*) ;; *) >&2 echo "This script current only works on macOS"; exit 1 ;; esac;

__DEFAULT_PLIST="EFI/OC/Config.plist"
__PLIST="${1:-$__DEFAULT_PLIST}"

echo "Generating public Config.plist..."

cp -f $__PLIST EFI/OC/Config.public.plist && \
/usr/libexec/PlistBuddy -c "Set :PlatformInfo:Generic:MLB M0000000000000001" EFI/OC/Config.public.plist && \
/usr/libexec/PlistBuddy -c "Set :PlatformInfo:Generic:SystemSerialNumber W00000000001" EFI/OC/Config.public.plist && \
/usr/libexec/PlistBuddy -c "Set :PlatformInfo:Generic:SystemUUID 00000000-0000-0000-0000-000000000000" EFI/OC/Config.public.plist

echo "Public Config.plist has been generated: 'EFI/OC/Config.public.plist'"

[ $__PLIST = $__DEFAULT_PLIST ] || { echo ""; echo 'Use `--no-verify` to commit this changes'; }
