#!/bin/sh

execute() {
	OC_SIGNING_MULTIPASS_INSTANCE=${OC_SIGNING_MULTIPASS_INSTANCE:-"primary"}
	case "$OSTYPE" in
		"darwin"* )
			eval multipass exec ${OC_SIGNING_MULTIPASS_INSTANCE} -- $@
		;;
		* )
			eval $@
		;;
	esac
}
