#!/bin/sh
#
# Copyright (c) 2015 Roderick W. Smith.
# Copyright (c) 2021 profzei.
# Copyright (c) 2024 null2264.
# SPDX-License-Identifier: GPL-3.0-only
#

. ./signing-common  # import execute

# 0.8.7
VERSION=$1

[ -z "$1" ] && { echo "Usage: signed-opencore-downloader [oc version]"; exit 1; }

# Download and unzip OpenCore
wget "https://github.com/acidanthera/OpenCorePkg/releases/download/${VERSION}/OpenCore-${VERSION}-RELEASE.zip"
unzip "OpenCore-${VERSION}-RELEASE.zip" "X64/*" -d "./Downloaded"
rm "OpenCore-${VERSION}-RELEASE.zip"

# Download HfsPlus
wget https://github.com/acidanthera/OcBinaryData/raw/master/Drivers/HfsPlus.efi -O ./Downloaded/X64/EFI/OC/Drivers/HfsPlus.efi

# Sign drivers by recursively looking for the .efi files in ./Downloaded directory
# Don't sign files that start with the dot, as this is metadata files
# Andrew Blitss's contribution
./sign ./Downloaded/X64/EFI/**/*

# Clean
rm -rf Downloaded
echo "Cleaned..."
