name: Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: ./nix-build-oc

    - name: Archive build results
      run: tar -I zstd -cf build.tar.zst result/EFI

    - name: Upload build folder
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build.tar.zst
        if-no-files-found: error
        retention-days: 3

